### ISSUE TITLE
node.kind undefined

### ISSUE THREAD

**Issue by ShawnXu** [pspeter3/gulp-tsfmt#10]
my typescript version is 1.8.10

gulpfile.js 

```
var tsfmt = require("gulp-tsfmt");

gulp.task('format', () => {
  gulp.src('app/**/*.ts')
    .pipe(tsfmt({options: {
      IndentSize: 2,
      TabSize: 2,
      NewLineCharacter: "\n",
      ConvertTabsToSpaces: true,
      InsertSpaceAfterCommaDelimiter: true,
      InsertSpaceAfterSemicolonInForStatements: true,
      InsertSpaceBeforeAndAfterBinaryOperators: true,
      InsertSpaceAfterKeywordsInControlFlowStatements: true,
      InsertSpaceAfterFunctionKeywordForAnonymousFunctions: false,
      InsertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis: false,
      PlaceOpenBraceOnNewLineForFunctions: false,
      PlaceOpenBraceOnNewLineForControlBlocks: false
    }}))
    .pipe(gulp.dest(file => path.dirname(file.path)));
});
```

```
$ gulp format
[11:13:38] Using gulpfile c:\Users\shawn\Desktop\photon-ui\gulpfile.js
[11:13:38] Starting 'format'...
[11:13:38] Finished 'format' after 54 ms
c:\Users\shawn\Desktop\photon-ui\node_modules\typescript\lib\typescript.js:6208
        switch (node.kind) {
                    ^

TypeError: Cannot read property 'kind' of undefined
    at Object.isExpression (c:\Users\shawn\Desktop\photon-ui\node_modules\typescript\lib\typescript.js:6208:21)
    at Function.Rules.NodeIsInDecoratorContext (c:\Users\shawn\Desktop\photon-ui\node_modules\typescript\lib\typescript.js:50340:27)
    at Rules.IsEndOfDecoratorContextOnSameLine (c:\Users\shawn\Desktop\photon-ui\node_modules\typescript\lib\typescript.js:50336:27)
    at RuleOperationContext.InContext (c:\Users\shawn\Desktop\photon-ui\node_modules\typescript\lib\typescript.js:49872:26)
    at RulesMap.GetRule (c:\Users\shawn\Desktop\photon-ui\node_modules\typescript\lib\typescript.js:50457:52)
    at processPair (c:\Users\shawn\Desktop\photon-ui\node_modules\typescript\lib\typescript.js:51436:56)
    at processRange (c:\Users\shawn\Desktop\photon-ui\node_modules\typescript\lib\typescript.js:51425:29)
    at consumeTokenAndAdvanceScanner (c:\Users\shawn\Desktop\photon-ui\node_modules\typescript\lib\typescript.js:51346:37)
    at processChildNode (c:\Users\shawn\Desktop\photon-ui\node_modules\typescript\lib\typescript.js:51275:25)
    at c:\Users\shawn\Desktop\photon-ui\node_modules\typescript\lib\typescript.js:51222:21
    at visitNode (c:\Users\shawn\Desktop\photon-ui\node_modules\typescript\lib\typescript.js:8103:20)
    at Object.forEachChild (c:\Users\shawn\Desktop\photon-ui\node_modules\typescript\lib\typescript.js:8160:21)
    at processNode (c:\Users\shawn\Desktop\photon-ui\node_modules\typescript\lib\typescript.js:51221:20)
    at processChildNode (c:\Users\shawn\Desktop\photon-ui\node_modules\typescript\lib\typescript.js:51280:21)
    at processChildNodes (c:\Users\shawn\Desktop\photon-ui\node_modules\typescript\lib\typescript.js:51316:48)
    at c:\Users\shawn\Desktop\photon-ui\node_modules\typescript\lib\typescript.js:51224:21
```

**Comment by ShawnXu** [comment]
With a bit of googling, I've tried updating typescript to typescript@next, problem remains. I wonder if that's a thing in the plugin itself.
